#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	fwk_lwip.o
obj-y	+=	fwk_udp.o
obj-y	+=	fwk_tcp.o
obj-y	+=	fwk_icmp.o

# end of file
