#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	zynq7_common.o
obj-y	+=	zynq7_led.o
obj-y	+=	zynq7_console.o
obj-y	+=	zynq7_systick.o
obj-y	+=	zynq7_hrtimer.o
obj-y	+=	zynq7_sdmmc.o

#obj-y	+=	zynq7_hdmi.o

obj-y	+=	board_init.o

# end of file
