#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-$(CONFIG_GPIO_IMX6)	+=	imx-gpiochip.o
obj-$(CONFIG_GPIO_IMX_LED)	+=	led_gpio.o

# end of file
