#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	thread_table.o

obj-y	+=	light_app.o
obj-y	+=	button_app.o
obj-y	+=	display_app.o
obj-y	+=	tsc_app.o
obj-y	+=	env_monitor.o

# end of file
