#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	thread_table.o

obj-$(CONFIG_LIGHT_APP)			+=	light_app.o
obj-$(CONFIG_BUTTON_APP)		+=	button_app.o
obj-$(CONFIG_DISPLAY_APP)		+=	display_app.o
obj-$(CONFIG_TSC_APP)			+=	tsc_app.o
obj-$(CONFIG_ENV_MONITOR_APP)	+=	env_monitor.o

# end of file
