#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.15
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	fwk_pinctrl.o
obj-y	+=	fwk_pinmux.o
obj-y	+=	fwk_pinconf.o

# end of file
