#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	errors.o
obj-y	+=	api_string.o
obj-y	+=	io_stream.o
obj-y	+=	time.o

# end of file
