#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-$(CONFIG_CLOCK_IMX6)	+=	imx-clks.o
obj-$(CONFIG_CLOCK_ZYNQ)	+=	zynq7-clks.o

# end of file
