#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.06.10
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

# ---------------------------------------------------- 
obj-y	+=	sysfs.o
obj-y	+=	kobjmap.o
obj-y	+=	chardev.o

# ---------------------------------------------------- 
obj-y	+=	fbmem.o

# end of file
