#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.12.21
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+= info.o
obj-y	+= ts.o
obj-y	+= ttc.o
obj-y	+= user.o
obj-y	+= kill.o
obj-y	+= history.o
obj-y	+= mem.o
obj-y	+= runtime.o
obj-y	+= value.o
obj-y	+= cpuinfo.o

# end of file
