#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	kthread/

obj-y	+=	sched.o
obj-y	+=	sleep.o
obj-y	+=	thread.o
obj-y	+=	spinlock.o
obj-y	+=	mutex.o
