#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	imx_common.o
obj-y	+=	imx6_led.o
obj-y	+=	imx6_systick.o
obj-y	+=	imx6_console.o
obj-y	+=	imx6_sdmmc.o
obj-y	+=	board_init.o

# end of file
