#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	mem/
obj-y	+=	bus_type/
obj-y	+=	of/

obj-y	+=	fwk_uaccess.o
obj-y	+=	fwk_fcntl.o
obj-y	+=	fwk_fs.o
obj-y	+=	fwk_kobjmap.o
obj-y	+=	fwk_inode.o

obj-y	+=	clk/
obj-y	+=	irq/
obj-y	+=	pinctrl/
obj-y	+=	gpio/
obj-y	+=	i2c/

obj-y	+=	chardev/
# obj-y	+=	blk_device/
obj-y	+=	net_device/

obj-y	+=	framebuffer/
obj-y	+=	mmc/
obj-y	+=	usb/

# end of file
