#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	base/
obj-y	+=	clk/

obj-$(CONFIG_PINCTRL)	+=	pinctrl/
obj-y	+=	gpio/

obj-$(CONFIG_INPUTDEV)	+=	input/
obj-$(CONFIG_I2C)	+=	i2c/
obj-$(CONFIG_USB)	+=	usb/
obj-$(CONFIG_VIDEO)	+=	video/

# end of file
