#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	clk/
obj-y	+=	pinctrl/
obj-y	+=	gpio/
obj-y	+=	input/
obj-y	+=	i2c/
obj-y	+=	usb/
obj-y	+=	video/

# end of file
