#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-$(CONFIG_INPUT_IMX_KEY)	+=	extkey.o
obj-$(CONFIG_SDK_KEY_ZYNQ) += zynq7sdk_key.o

# end of file
