#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	imx6ull/

# obj-y	+=	start.o
obj-y	+=	lowlevel_init.o
obj-y	+=	irq.o
