#define CONFIG_ARCH "arm"
#define CONFIG_TYPE "armv7"
#define CONFIG_CLASS "cortex-a9"
#define CONFIG_VERDOR "xilinx"
#define CONFIG_CPU "xc7z010"
#define CONFIG_COMPILER "arm-none-eabi-"
#define CONFIG_ARCH_ARMV7 1
#define CONFIG_LITTILE_ENDIAN 1
#define CONFIG_VFP 1
#define CONFIG_INSTRUCTION arm
#define CONFIG_BUILD_TYPE release
#define CONFIG_OPTIMIZE 2
#define CONFIG_HZ 1000
#define CONFIG_HRTIMER_ENBALE 1
#define CONFIG_CONSOLE_DEVICE "/dev/uart0"
#define CONFIG_XTAL_FREQ_CLK (24000000)
#define CONFIG_RTC_FREQ_CLK (32768)
#define CONFIG_CPU_FREQ (666666687)
#define CONFIG_RAM_DDR_BASE (0x00100000)
#define CONFIG_RAM_DDR_SIZE (0x0FF00000)
#define CONFIG_PROGRAM_OFFSET (0x04000000)
#define CONFIG_PROGRAM_BASE (CONFIG_RAM_DDR_BASE + CONFIG_PROGRAM_OFFSET)
#define CONFIG_PROGRAM_SIZE (CONFIG_RAM_DDR_SIZE - CONFIG_PROGRAM_OFFSET)
#define CONFIG_BOARD_SP_ADDR (0x00900000)
#define CONFIG_BOOT_MALLOC_LEN (2 * 1024 * 1024)
#define CONFIG_B2K_PARAM_BASE (CONFIG_BOARD_SP_ADDR)
#define CONFIG_B2K_PARAM_SIZE (16 * 1024 * 1024)
#define CONFIG_DEVICE_TREE_BASE (0x02100000)
#define CONFIG_FDT_MAX_SIZE (4 * 1024 * 1024)
#define CONFIG_B2K_FIXDATA_BASE (0x02500000)
#define CONFIG_B2K_FIXDATA_SIZE (24 * 1024 * 1024)
#define CONFIG_DMA_AREA_SIZE (16 * 1024 * 1024)
#define CONFIG_FB_DRAM_SIZE (16 * 1024 * 1024)
#define CONFIG_NETWORK_BUFF_SIZE (8 * 1024 * 1024)
#define CONFIG_STACK_WITH_LDS 1
#define CONFIG_SYS_STACK_SIZE (2 * 1024 * 1024)
#define CONFIG_SVC_STACK_SIZE (8 * 1024 * 1024)
#define CONFIG_ABT_STACK_SIZE (4 * 1024)
#define CONFIG_IRQ_STACK_SIZE (8 * 1024 * 1024)
#define CONFIG_FIQ_STACK_SIZE (2 * 1024 * 1024)
#define CONFIG_UND_STACK_SIZE (4 * 1024)
#define CONFIG_HEAP_SIZE (8 * 1024 * 1024)
#define CONFIG_STACK_BASE (CONFIG_BOARD_SP_ADDR 	+ CONFIG_B2K_PARAM_SIZE)
#define CONFIG_UND_STACK_BASE (CONFIG_STACK_BASE      + CONFIG_UND_STACK_SIZE)
#define CONFIG_FIQ_STACK_BASE (CONFIG_UND_STACK_BASE  + CONFIG_FIQ_STACK_SIZE)
#define CONFIG_IRQ_STACK_BASE (CONFIG_FIQ_STACK_BASE  + CONFIG_IRQ_STACK_SIZE)
#define CONFIG_ABT_STACK_BASE (CONFIG_IRQ_STACK_BASE  + CONFIG_ABT_STACK_SIZE)
#define CONFIG_SVC_STACK_BASE (CONFIG_ABT_STACK_BASE  + CONFIG_SVC_STACK_SIZE)
#define CONFIG_SYS_STACK_BASE (CONFIG_SVC_STACK_BASE  + CONFIG_SYS_STACK_SIZE)
#define CONFIG_LCD_PIXELBIT (32)
#define CONFIG_OF 1
#define CONFIG_BLOCK_DEVICE 1
#define CONFIG_PINCTRL 1
#define CONFIG_MMC 1
#define CONFIG_UART 1
#define CONFIG_I2C 1
#define CONFIG_DMA 1
#define CONFIG_INPUTDEV 1
#define CONFIG_VIDEO 1
#define CONFIG_USB 1
#define CONFIG_FB_MULTI_SUPPORT 1
#define CONFIG_FBUFFER_NUM 2
#define CONFIG_CPU_ZYNQ 1
#define CONFIG_CLOCK_ZYNQ 1
#define CONFIG_SDK_LED_ZYNQ 1
#define CONFIG_SDK_HDMI_ZYNQ 1
#define CONFIG_SDK_GEM_ZYNQ 1
#define CONFIG_DISPLAY_APP 1
#define CONFIG_LIGHT_APP 1
#define CONFIG_CONSOLE_APP 1
#define CONFIG_NETWORK_TASK 1
#define CONFIG_LVGL_TASK 1
