#define CONFIG_ARCH "arm"
#define CONFIG_TYPE "armv7"
#define CONFIG_CLASS "cortex-a7"
#define CONFIG_VERDOR "nxp"
#define CONFIG_CPU "imx6ull"
#define CONFIG_COMPILER "arm-linux-gnueabihf-"
#define CONFIG_ARCH_ARMV7 1
#define CONFIG_LITTILE_ENDIAN 1
#define CONFIG_VFP 1
#define CONFIG_INSTRUCTION arm
#define CONFIG_BUILD_TYPE debug
#define CONFIG_OPTIMIZE_CLASS 0
#define CONFIG_HZ (100)
#define CONFIG_HRTIMER_ENBALE 1
#define CONFIG_CONSOLE_DEVICE "/dev/uart0"
#define CONFIG_XTAL_FREQ_CLK (24000000)
#define CONFIG_RTC_FREQ_CLK (32768)
#define CONFIG_CPU_FREQ (792000000)
#define CONFIG_RAM_DDR_BASE (0x80000000)
#define CONFIG_RAM_DDR_SIZE (0x20000000)
#define CONFIG_PROGRAM_OFFSET (0x07800000)
#define CONFIG_PROGRAM_BASE (CONFIG_RAM_DDR_BASE + CONFIG_PROGRAM_OFFSET)
#define CONFIG_PROGRAM_SIZE (CONFIG_RAM_DDR_SIZE - CONFIG_PROGRAM_OFFSET)
#define CONFIG_BOARD_SP_ADDR (0x80800000)
#define CONFIG_BOOT_MALLOC_LEN (2 * 1024 * 1024)
#define CONFIG_B2K_PARAM_BASE (CONFIG_BOARD_SP_ADDR)
#define CONFIG_B2K_PARAM_SIZE (24 * 1024 * 1024)
#define CONFIG_DEVICE_TREE_BASE (0x86000000)
#define CONFIG_FDT_MAX_SIZE (4 * 1024 * 1024)
#define CONFIG_B2K_FIXDATA_BASE (0x84400000)
#define CONFIG_B2K_FIXDATA_SIZE (24 * 1024 * 1024)
#define CONFIG_DMA_AREA_SIZE (16 * 1024 * 1024)
#define CONFIG_FB_DRAM_SIZE (24 * 1024 * 1024)
#define CONFIG_NETWORK_BUFF_SIZE (8 * 1024 * 1024)
#define CONFIG_STACK_WITH_LDS 1
#define CONFIG_SYS_STACK_SIZE (2 * 1024 * 1024)
#define CONFIG_SVC_STACK_SIZE (8 * 1024 * 1024)
#define CONFIG_ABT_STACK_SIZE (4 * 1024)
#define CONFIG_IRQ_STACK_SIZE (8 * 1024 * 1024)
#define CONFIG_FIQ_STACK_SIZE (2 * 1024 * 1024)
#define CONFIG_UND_STACK_SIZE (4 * 1024)
#define CONFIG_HEAP_SIZE (8 * 1024 * 1024)
#define CONFIG_STACK_BASE (CONFIG_BOARD_SP_ADDR 	+ CONFIG_B2K_PARAM_SIZE)
#define CONFIG_UND_STACK_BASE (CONFIG_STACK_BASE      + CONFIG_UND_STACK_SIZE)
#define CONFIG_FIQ_STACK_BASE (CONFIG_UND_STACK_BASE  + CONFIG_FIQ_STACK_SIZE)
#define CONFIG_IRQ_STACK_BASE (CONFIG_FIQ_STACK_BASE  + CONFIG_IRQ_STACK_SIZE)
#define CONFIG_ABT_STACK_BASE (CONFIG_IRQ_STACK_BASE  + CONFIG_ABT_STACK_SIZE)
#define CONFIG_SVC_STACK_BASE (CONFIG_ABT_STACK_BASE  + CONFIG_SVC_STACK_SIZE)
#define CONFIG_SYS_STACK_BASE (CONFIG_SVC_STACK_BASE  + CONFIG_SYS_STACK_SIZE)
#define CONFIG_HEAP_BASE (CONFIG_SYS_STACK_BASE)
#define CONFIG_LCD_PIXELBIT (32)
#define CONFIG_OF 1
#define CONFIG_PINCTRL 1
#define CONFIG_MMC 1
#define CONFIG_UART 1
#define CONFIG_I2C 1
#define CONFIG_DMA 1
#define CONFIG_INPUTDEV 1
#define CONFIG_VIDEO 1
#define CONFIG_USB 1
#define CONFIG_FBUFFER_NUM 2
#define CONFIG_CPU_IMX6 1
#define CONFIG_CLOCK_IMX6 1
#define CONFIG_GPIO_IMX6 1
#define CONFIG_GPIO_IMX_LED 1
#define CONFIG_PINCTRL_IMX6 1
#define CONFIG_INPUT_IMX_KEY 1
#define CONFIG_UART_IMX6 1
#define CONFIG_I2C_IMX6 1
#define CONFIG_I2C_AP3216C 1
#define CONFIG_I2C_AT24CXX 1
#define CONFIG_I2C_TSC2007 1
#define CONFIG_SDMA_IMX6 1
#define CONFIG_HDMI_SIL9022A 1
#define CONFIG_SDMMC_BUS_WIDTH 1
#define CONFIG_VIDEO_FB_IMX6 1
#define CONFIG_USB_IMX6 1
#define CONFIG_USB_GADGET_IMX6 1
#define CONFIG_USB_IMX_MOUSE 1
#define CONFIG_BUTTON_APP 1
#define CONFIG_DISPLAY_APP 1
#define CONFIG_ENV_MONITOR_APP 1
#define CONFIG_LIGHT_APP 1
