#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.05.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	imx-i2c.o
obj-y	+=	tsc2007.o
obj-y	+=	ap3216c.o
obj-y	+=	at24cxx.o

# end of file
