#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.05.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-$(CONFIG_I2C_IMX6)	+=	imx-i2c.o

obj-$(CONFIG_I2C_TSC2007)	+=	tsc2007.o
obj-$(CONFIG_I2C_AP3216C)	+=	ap3216c.o
obj-$(CONFIG_I2C_AT24CXX)	+=	at24cxx.o

# end of file
