#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

# obj-y	+=	cc932.o
# obj-y	+=	cc936.o
# obj-y	+=	cc949.o
# obj-y	+=	cc950.o
# obj-y	+=	ccsbcs.o

obj-y	+=	unicode.o

# end of file
