#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	fwk_uaccess.o
obj-y	+=	fwk_fcntl.o
obj-y	+=	fwk_fs.o
obj-y	+=	fwk_kobjmap.o
obj-y	+=	fwk_kobject.o
obj-y	+=	fwk_inode.o

# end of file
