#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	fwk_irq.o
obj-y	+=	fwk_irq_domain.o
obj-y	+=	fwk_irq_desc.o
obj-y	+=	fwk_irq_types.o
