#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.05.03
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	fwk_clk.o
obj-y	+=	fwk_clk_gate.o
obj-y	+=	fwk_clk_provider.o

# end of file
