#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.20
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-$(CONFIG_PINCTRL_IMX6)	+=	imx-iomuxc.o

# end of file
